### PR TITLE
Closes #49: Detect untested files

### LINKED ISSUE #49: Coverage warnings are missing for completely untested files
When running `yarn test`, the build system notifies the builder about any files with a coverage lower than 90%. Unfortunately, it completely ignores files that are entirely untested, as it never invokes the coverage suggestion tool. The aforementioned gives an incorrect overview of the coverage and should be corrected.

### PR DESCRIPTION
**Pull request by NiclasHedam**
As discussed in person, precise heuristics to detect untested files are required. These heuristics must not create false positives.

This initial version extends the prepare method to look for source files without an associated test file. The unassociated files will then be compiled to search for exported functions.

### CODE REVIEW

**Comment by NiclasHedam** [comment]
By the way; this solution is modular. It is easy to add cases to which testing is required.

File: scripts/prepare.js [hunk 1]
```diff
@@ -35,11 +40,71 @@ for (const pkg of packages) {
...
+      path.join(dir, `${path.basename(file, ".ts")}.spec.tsx`)
+    ];
+
+    if (potentialTestFiles.some(file => isFile(file))) {
+      continue; // An associated test file was found
+    }
+
+    const compiled = TypeScript.createSourceFile(
+      "anon.ts",
+      fs.readFileSync(file).toString(),
```
Comment (kasperisager) [inline scripts/prepare.js]: Use `readFile()` from `file-system.js`.

File: scripts/prepare.js [hunk 2]
```diff
@@ -35,11 +40,71 @@ for (const pkg of packages) {
...
+      path.join(dir, `${path.basename(file, ".ts")}.spec.ts`),
+      // TSX source with TS test file
+      path.join(dir, `${path.basename(file, ".tsx")}.spec.ts`),
+      // TSX source with TSX test file
+      path.join(dir, `${path.basename(file, ".tsx")}.spec.tsx`),
+      // TS source with TSX test file
+      path.join(dir, `${path.basename(file, ".ts")}.spec.tsx`)
+    ];
+
+    if (potentialTestFiles.some(file => isFile(file))) {
```
Comment (kasperisager) [inline scripts/prepare.js]: No need to wrap in another lambda:

```ts
potentialTestFiles.some(isFile)
```
