### PR TITLE
R66/R69 should ignore elements that are used in name of disabled widgets

### LINKED ISSUE #1149: R66/R69 should ignore elements that are used in name of disabled widgets
ACT rule and Sanshikan currently have this exception, but Alfa hasn't.

Gather all `aria-disabled` widgets on the document, compute their name, filter out the text nodes that take part in these names.

### PR DESCRIPTION
**Pull request by zsofitoth**
Resolves #1149

### CODE REVIEW

**Comment by zsofitoth** [comment]
For now it's only for R66 - after the review I will apply it to R69 as well. I'm not sure if they should somehow share `disabledWidgetNames` and `textNodes` though to not compute those twice.

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 1]
```diff
@@ -35,31 +36,66 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
               ),
               node
             )
           ) {
-            return;
+            // Compute the names of these elements
+            const names = node.attributes
+              .filter((attribute) => attribute.name === "name")
+              .map((attribute) => attribute.value);
+            disabledWidgetNames = disabledWidgetNames.concat(names);
```
Comment (Jym77) [inline packages/alfa-rules/src/sia-r66/rule.ts:83]: This should be about their accessible name, not the `name` attribute.
So, something like `ariaNode.from(node, device).name`.

The name does contain a `source` which recursively contains all nodes taking part in the computation: https://github.com/Siteimprove/alfa/blob/main/packages/alfa-aria/src/name.ts#L86-L91
(it may be worth to have the source implement `Iterable<dom.Node>` so they can each iterate the nodes taking part in their computation and we can just use this iterator here, this is done like that: https://github.com/Siteimprove/alfa/blob/main/packages/alfa-selector/src/selector.ts#L131-L133)

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 2]
```diff
@@ -35,31 +36,66 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
-          if (test(and(isText, isPerceivableForAll(device)), node)) {
-            yield node;
+          for (const child of node.children(Node.fullTree)) {
+            gather(child);
           }
+        }
 
-          for (const child of node.children(Node.fullTree)) {
-            yield* visit(child);
+        function* getApplicableLinks(): Iterable<Text> {
```
Comment (Jym77) [inline packages/alfa-rules/src/sia-r66/rule.ts:91]:
```suggestion
        function* getApplicableTexts(): Iterable<Text> {
```

File: packages/alfa-rules/test/sia-r66/rule.spec.tsx [hunk 3]
```diff
@@ -262,6 +262,19 @@ test("evaluate() is inapplicable to text nodes in disabled groups", async (t) =>
   t.deepEqual(await evaluate(R66, { document }), [inapplicable(R66)]);
 });
 
+test("evaluate() is inapplicable to elements that are used in name of disabled widgets", async (t) => {
+  const document = h.document([
+    <html>
+      <fieldset name="Disabled widget name" disabled>
+        <button>Hello world</button>
+      </fieldset>
+      <div>widget name</div>
```
Comment (Jym77) [inline packages/alfa-rules/test/sia-r66/rule.spec.tsx:271]:
```suggestion
      <fieldset aria-labelledby="label" disabled>
        <button>Hello world</button>
      </fieldset>
      <div id="label">widget name</div>
```
(but a different `<div>widget name</div>` would be applicable)

**Review by Jym77 — CHANGES_REQUESTED** [review]

**Comment by Jym77** [comment]
> For now it's only for R66 - after the review I will apply it to R69 as well. I'm not sure if they should somehow share `disabledWidgetNames` and `textNodes` though to not compute those twice.

Ideally, we'd want to share it of course. But that is likely a topic for #1139

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 4]
```diff
@@ -35,31 +37,68 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
+        let textNodes: Sequence<Text> = Sequence.empty();
 
-        function* visit(node: Node): Iterable<Text> {
+        gather(document);
+        return getApplicableTexts();
+
+        function gather(node: Node): void {
+          // Gather all applicable text nodes
+          if (
+            node.parent().isSome() &&
```
Comment (Jym77) [inline packages/alfa-rules/src/sia-r66/rule.ts:49]:
```suggestion
            node.parent().some(…
```
Will take a predicate as argument and automatically be `false` if the option is `None`.

**Review by Jym77 — CHANGES_REQUESTED** [review]
Looks good. Some refactoring.

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 5]
```diff
@@ -35,31 +37,68 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
+        }
 
-          for (const child of node.children(Node.fullTree)) {
-            yield* visit(child);
+        function* getApplicableTexts(): Iterable<Text> {
+          // Filter out text nodes that are contained in disabledWidgetNames
+          for (const textNode of textNodes) {
+            if (disabledWidgetTexts.none((text) => text.equals(textNode))) {
+              yield textNode;
+            }
```
[the remark this answers is not in the document]
Comment (zsofitoth) [reply packages/alfa-rules/src/sia-r66/rule.ts]: Tried to do the filtering as part of `gather`, but didn't work with:
https://act-rules.github.io/rules/afw4f7#inapplicable-example-8
As the `input` and `text` there are siblings

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 6]
```diff
@@ -35,31 +37,67 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
           if (
             test(
               and(
                 isElement,
                 or(
-                  not(hasNamespace(Namespace.HTML)),
                   hasRole(device, (role) => role.isWidget()),
-                  and(hasRole(device, "group"), isSemanticallyDisabled)
+                  isSemanticallyDisabled
                 )
```
Comment (Jym77) [inline packages/alfa-rules/src/sia-r66/rule.ts:54]: This should be a `and` (to get disabled widgets: both widget and disabled).
So
```html
<label>
  some text
  <input />
</label>
```
the text is in the name of an active widget and should be tested.

**Review by Jym77 — CHANGES_REQUESTED** [review]

File: packages/alfa-rules/src/sia-r66/rule.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (Jym77) [reply packages/alfa-rules/src/sia-r66/rule.ts]: 🤔 I'm not sure I see why tris cause a problem. By pre-computing the `disableWidgetTexts` we should see that the label is one and correctly be able to filter it out (which is what `getApplicabelTexts` is already doing).
So

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 7]
```diff
@@ -35,6 +37,34 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
+                  and(
+                    or(
+                      hasRole(device, (role) => role.isWidget()),
+                      hasRole(device, "group")
+                    ),
+                    isSemanticallyDisabled
+                  )
+                ),
+                node
+              )
```
Comment (Jym77) [inline packages/alfa-rules/src/sia-r66/rule.ts:57]: Looks like this can be eta-contracted and the call to `test` removed.
```suggestion
            .filter(and(
                  isElement,
                  and(
                    or(
                      hasRole(device, (role) => role.isWidget()),
                      hasRole(device, "group")
                    ),
                    isSemanticallyDisabled
                  )
                )
```

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 8]
```diff
@@ -35,6 +37,34 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
...
+          document
+            .descendants(Node.fullTree)
+            .filter((node) =>
+              test(
+                and(
+                  isElement,
+                  and(
+                    or(
+                      hasRole(device, (role) => role.isWidget()),
+                      hasRole(device, "group")
```
Comment (Jym77) [inline packages/alfa-rules/src/sia-r66/rule.ts:51]: We can probably one-line these
```suggestion
                      hasRole(device, (role) => role.isWidget() || role.is("group"))
```

**Review by Jym77 — CHANGES_REQUESTED** [review]
Great. Some more polishing 😅

File: packages/alfa-rules/src/sia-r66/rule.ts [hunk 9]
```diff
@@ -54,7 +84,10 @@ export default Rule.Atomic.of<Page, Text, Question.Metadata>({
             return;
           }
 
-          if (test(and(isText, isPerceivableForAll(device)), node)) {
+          if (
+            test(and(isText, isPerceivableForAll(device)), node) &&
+            !disabledWidgetTexts.has(node)
```
[the remark this answers is not in the document]
Comment (zsofitoth) [reply packages/alfa-rules/src/sia-r66/rule.ts:88]: It doesn't quite work with the `isText` as the `node` is still type of `Node` there and the compiler is not happy because in `disabledWidgetTexts` there are `Text`s

[the remark this answers is not in the document]
Comment (Jym77) [reply packages/alfa-rules/src/sia-r66/rule.ts:88]: Ah yes, the first `and(isText, …)` should be a `Refinement.and` so that the second `and(isPerceivable, not(set.has))` only receives `Text`. 🤔 (also maybe wrong parenthesis in the suggestion 🙃 should be `and(isText, and(isPerceivable, not(set.has)))`)

**Review by Jym77 — APPROVED** [review]
