### PR TITLE
SIA-R87: Ask if the first focusable element is visible on focus

### LINKED ISSUE #757: SIA-R87 should ask for input rather than fail when the first focusable link cannot be determined to be visible on focus
- [ ] Follow up on DEV-11496.
- [ ] Follow up on DEV-11988.

### PR DESCRIPTION
**Pull request by elenamongelli**
Resolves #757

### CODE REVIEW

File: packages/alfa-rules/src/sia-r87/rule.ts [hunk 1]
```diff
@@ -14,10 +15,11 @@ import { hasRole } from "../common/predicate/has-role";
 import { isDocumentElement } from "../common/predicate/is-document-element";
 import { isTabbable } from "../common/predicate/is-tabbable";
 import { isIgnored } from "../common/predicate/is-ignored";
-import { isKeyboardActionable } from "../common/predicate/is-keyboard-actionable";
+import { isVisible } from "../common/predicate/is-visible";
 
 import { Question } from "../common/question";
 import { isAtTheStart } from "../common/predicate/is-at-the-start";
+import { Option } from "@siteimprove/alfa-option";
```
Comment (kasperisager) [inline packages/alfa-rules/src/sia-r87/rule.ts:22]: This should be moved to the top with the rest of the `@siteimprove/alfa-*` imports.

File: packages/alfa-rules/test/sia-r87/rule.spec.tsx [hunk 2]
```diff
@@ -213,11 +213,73 @@ test(`evaluate() fails a document whose first tabbable link is not visible`, asy
...
+    ),
+    [
+      failed(R87, document, {
+        1: Outcomes.FirstTabbableIsNotVisible,
+      }),
+    ]
+  );
+});
+
+test(`evaluate() fails a document whose first tabbable link is not visible`, async (t) => {
```
Comment (kasperisager) [inline packages/alfa-rules/test/sia-r87/rule.spec.tsx:232]: This tests a passed outcome.

File: packages/alfa-rules/test/sia-r87/rule.spec.tsx [hunk 3]
```diff
@@ -213,11 +213,73 @@ test(`evaluate() fails a document whose first tabbable link is not visible`, asy
...
+    ),
+    [
+      passed(R87, document, {
+        1: Outcomes.FirstTabbableIsLinkToContent,
+      }),
+    ]
+  );
+});
+
+test(`evaluate() fails a document whose first tabbable link is not visible`, async (t) => {
```
Comment (kasperisager) [inline packages/alfa-rules/test/sia-r87/rule.spec.tsx:265]: This tests a can't tell outcome.

**Review by kasperisager — DISMISSED** [review]

**Review by kasperisager — APPROVED** [review]
