### PR TITLE
SIA-ER62: `background-image` should ignore transparent link element

### LINKED ISSUE #1131: R62: Comparing `background-image` should ignore transparent link element
We currently accept any difference in `background-image` between link and container, which is incorrect since a fully transparent `background` on the link results in no difference, even if the `background` image is technically different (between some image and `none`).

We should add the same logic of "if the link's background is transparent, `background-image` is not a distinguishing factor" as what happens when comparing `background-color`.

- [ ] Follow up on CE-5894

### PR DESCRIPTION
**Pull request by zsofitoth**
Resolves #1131

### CODE REVIEW

File: packages/alfa-rules/src/sia-er62/rule.ts [hunk 1]
```diff
@@ -522,9 +522,18 @@ namespace Distinguishable {
...
       hasComputedStyle(
         "background-image",
-        not((image) => image.equals(imageReference)),
+        not((image) => {
+          let hasNoBackgroundImage: boolean = false;
+          for (const value of image.values) {
+            if (Keyword.isKeyword(value) && value.equals(Keyword.of("none"))) {
+              hasNoBackgroundImage = true;
+            }
+          }
```
Comment (zsofitoth) [inline packages/alfa-rules/src/sia-er62/rule.ts:534]: This is not super elegant, but it turns out when it comes to the `background-image` property, transparent means that the value of the css property is `none`.

Comment (Jym77) [reply packages/alfa-rules/src/sia-er62/rule.ts:534]: 🤔 I feel we should merge both transparent tests. Something like `hasNoBackground = [color: transparent] and [image: none]` . That will make the logic more apparent and a bit safer.

**Review by Jym77 — CHANGES_REQUESTED** [review]

**Review by Jym77 — APPROVED** [review]
