### PR TITLE
SIA R53: ignore headings that are not in the accessibility tree

### LINKED ISSUE #576: SIA-R53 should not apply to headings not in the accessibility tree as these have no level
The following case currently fails the rule:

```html
<h3 hidden>Foo</h3>
<h5>Bar</h5>
```

- [ ] Follow up on DEV-10889.

### PR DESCRIPTION
**Pull request by Jym77**
Closes #576.

### CODE REVIEW

File: packages/alfa-rules/src/sia-r53/rule.ts [hunk 1]
```diff
@@ -18,7 +19,8 @@ export default Rule.Atomic.of<Page, Element>({
     const headings = document
       .descendants({ flattened: true })
       .filter(isElement)
-      .filter(hasRole("heading"));
+      .filter(hasRole("heading"))
+      .filter(not(isIgnored(device)));
```
Comment (kasperisager) [inline packages/alfa-rules/src/sia-r53/rule.ts:23]:
```suggestion
      .reject(isIgnored(device));
```

File: packages/alfa-rules/src/sia-r53/rule.ts [hunk 2]
```diff
@@ -8,8 +8,9 @@ import { expectation } from "../common/expectation";
 
 import { hasHeadingLevel } from "../common/predicate/has-heading-level";
 import { hasRole } from "../common/predicate/has-role";
+import { isIgnored } from "../common/predicate/is-ignored";
 
-const { and, equals } = Predicate;
+const { equals, not } = Predicate;
```
Comment (kasperisager) [inline packages/alfa-rules/src/sia-r53/rule.ts:13]:
```suggestion
const { equals } = Predicate;
```

**Review by kasperisager — CHANGES_REQUESTED** [review]
Looks great! 👌 Just a minor, erh, editorial?

**Review by kasperisager — APPROVED** [review]
